version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - ivyhjk
  assignees:
  - ivyhjk
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: eslint
    versions:
    - 7.22.0
